### ISSUE TITLE
versioneye plugin (version 2.0.0) is not compatible with maven 3.1.x

### ISSUE THREAD

**Issue by hakan42** [versioneye/versioneye_maven_plugin#11]
Running with maven 3.1.1 gives the java.lang.ClassNotFoundException: org.sonatype.aether.RepositorySystem:

```
C:\path-to-my-project>mvn -v
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: C:\path-to-my-maven-installation\apache-maven-3.1.1\bin\..
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: c:\work\jdk1.7.0_45\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

calling "mvn versions:ping" gives:

```
[INFO] --- versioneye-maven-plugin:2.0.0:ping (default-cli) @ transifex ---
[WARNING] Error injecting: com.versioneye.PingMojo
java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystem;
        at java.lang.Class.getDeclaredFields0(Native Method)
....
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.RepositorySystem
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
```

The same works perfectly with Maven 3.0.4
